# SPDX-License-Identifier: Apache-2.0

# Copyright 2020, 2021 igo95862

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from .notcurses import (
    NcPlane, Notcurses, NcInput, NotcursesOptions, NcPlaneOptions,
    NCOPTION_INHIBIT_SETLOCALE, NCOPTION_NO_CLEAR_BITMAPS,
    NCOPTION_NO_WINCH_SIGHANDLER, NCOPTION_NO_QUIT_SIGHANDLERS,
    NCOPTION_PRESERVE_CURSOR, NCOPTION_SUPPRESS_BANNERS,
    NCOPTION_NO_ALTERNATE_SCREEN, NCOPTION_NO_FONT_CHANGES,
    NCOPTION_DRAIN_INPUT, NCOPTION_SCROLLING, NCOPTION_CLI_MODE,
    NCKEY_INVALID, NCKEY_RESIZE, NCKEY_UP, NCKEY_RIGHT, NCKEY_DOWN, NCKEY_LEFT,
    NCKEY_INS, NCKEY_DEL, NCKEY_BACKSPACE, NCKEY_PGDOWN, NCKEY_PGUP, NCKEY_HOME,
    NCKEY_END, NCKEY_F00, NCKEY_F01, NCKEY_F02, NCKEY_F03, NCKEY_F04, NCKEY_F05,
    NCKEY_F06, NCKEY_F07, NCKEY_F08, NCKEY_F09, NCKEY_F10, NCKEY_F11, NCKEY_F12,
    NCKEY_F13, NCKEY_F14, NCKEY_F15, NCKEY_F16, NCKEY_F17, NCKEY_F18, NCKEY_F19,
    NCKEY_F20, NCKEY_F21, NCKEY_F22, NCKEY_F23, NCKEY_F24, NCKEY_F25, NCKEY_F26,
    NCKEY_F27, NCKEY_F28, NCKEY_F29, NCKEY_F30, NCKEY_F31, NCKEY_F32, NCKEY_F33,
    NCKEY_F34, NCKEY_F35, NCKEY_F36, NCKEY_F37, NCKEY_F38, NCKEY_F39, NCKEY_F40,
    NCKEY_F41, NCKEY_F42, NCKEY_F43, NCKEY_F44, NCKEY_F45, NCKEY_F46, NCKEY_F47,
    NCKEY_F48, NCKEY_F49, NCKEY_F50, NCKEY_F51, NCKEY_F52, NCKEY_F53, NCKEY_F54,
    NCKEY_F55, NCKEY_F56, NCKEY_F57, NCKEY_F58, NCKEY_F59, NCKEY_F60,
    NCKEY_ENTER, NCKEY_CLS, NCKEY_DLEFT, NCKEY_DRIGHT, NCKEY_ULEFT,
    NCKEY_URIGHT, NCKEY_CENTER, NCKEY_BEGIN, NCKEY_CANCEL, NCKEY_CLOSE,
    NCKEY_COMMAND, NCKEY_COPY, NCKEY_EXIT, NCKEY_PRINT, NCKEY_REFRESH,
    NCKEY_SEPARATOR, NCKEY_CAPS_LOCK, NCKEY_SCROLL_LOCK, NCKEY_NUM_LOCK,
    NCKEY_PRINT_SCREEN, NCKEY_PAUSE, NCKEY_MENU, NCKEY_MEDIA_PLAY,
    NCKEY_MEDIA_PAUSE, NCKEY_MEDIA_PPAUSE, NCKEY_MEDIA_REV, NCKEY_MEDIA_STOP,
    NCKEY_MEDIA_FF, NCKEY_MEDIA_REWIND, NCKEY_MEDIA_NEXT, NCKEY_MEDIA_PREV,
    NCKEY_MEDIA_RECORD, NCKEY_MEDIA_LVOL, NCKEY_MEDIA_RVOL, NCKEY_MEDIA_MUTE,
    NCKEY_LSHIFT, NCKEY_LCTRL, NCKEY_LALT, NCKEY_LSUPER, NCKEY_LHYPER,
    NCKEY_LMETA, NCKEY_RSHIFT, NCKEY_RCTRL, NCKEY_RALT, NCKEY_RSUPER,
    NCKEY_RHYPER, NCKEY_RMETA, NCKEY_L3SHIFT, NCKEY_L5SHIFT, NCKEY_MOTION,
    NCKEY_BUTTON1, NCKEY_BUTTON2, NCKEY_BUTTON3, NCKEY_BUTTON4, NCKEY_BUTTON5,
    NCKEY_BUTTON6, NCKEY_BUTTON7, NCKEY_BUTTON8, NCKEY_BUTTON9, NCKEY_BUTTON10,
    NCKEY_BUTTON11, NCKEY_SIGNAL, NCKEY_EOF, NCKEY_SCROLL_UP,
    NCKEY_SCROLL_DOWN, NCKEY_RETURN, NCKEY_TAB, NCKEY_ESC, NCKEY_SPACE,
    NCKEY_MOD_SHIFT, NCKEY_MOD_ALT, NCKEY_MOD_CTRL, NCKEY_MOD_SUPER,
    NCKEY_MOD_HYPER, NCKEY_MOD_META, NCKEY_MOD_CAPSLOCK, NCKEY_MOD_NUMLOCK,
    ncchannel_alpha, ncchannel_b, ncchannel_default_p,
    ncchannel_g, ncchannel_palindex, ncchannel_palindex_p, ncchannel_r,
    ncchannel_rgb8, ncchannel_rgb_initializer, ncchannel_set,
    ncchannel_set_alpha, ncchannel_set_default, ncchannel_set_palindex,
    ncchannel_set_rgb8, ncchannel_set_rgb8_clipped, ncchannels_bchannel,
    ncchannels_bg_alpha, ncchannels_bg_default_p, ncchannels_bg_palindex,
    ncchannels_bg_palindex_p, ncchannels_bg_rgb, ncchannels_bg_rgb8,
    ncchannels_combine, ncchannels_fchannel, ncchannels_fg_alpha,
    ncchannels_fg_default_p, ncchannels_fg_palindex,
    ncchannels_fg_palindex_p, ncchannels_fg_rgb, ncchannels_fg_rgb8,
    ncchannels_rgb_initializer, ncchannels_set_bchannel,
    ncchannels_set_bg_alpha, ncchannels_set_bg_default,
    ncchannels_set_bg_palindex, ncchannels_set_bg_rgb,
    ncchannels_set_bg_rgb8, ncchannels_set_bg_rgb8_clipped,
    ncchannels_set_fchannel, ncchannels_set_fg_alpha,
    ncchannels_set_fg_default, ncchannels_set_fg_palindex,
    ncchannels_set_fg_rgb, ncchannels_set_fg_rgb8,
    ncchannels_set_fg_rgb8_clipped, ncstrwidth, notcurses_version,
    notcurses_version_components,
    NCBOXASCII, NCBOXDOUBLE, NCBOXHEAVY, NCBOXLIGHT, NCBOXOUTER, NCBOXROUND,
    box, rgb,
)

__all__ = (
    'NcPlane', 'Notcurses', 'NcInput', 'NotcursesOptions', 'NcPlaneOptions',

    'NCOPTION_INHIBIT_SETLOCALE', 'NCOPTION_NO_CLEAR_BITMAPS',
    'NCOPTION_NO_WINCH_SIGHANDLER', 'NCOPTION_NO_QUIT_SIGHANDLERS',
    'NCOPTION_PRESERVE_CURSOR', 'NCOPTION_SUPPRESS_BANNERS',
    'NCOPTION_NO_ALTERNATE_SCREEN', 'NCOPTION_NO_FONT_CHANGES',
    'NCOPTION_DRAIN_INPUT', 'NCOPTION_SCROLLING', 'NCOPTION_CLI_MODE',

    'NCKEY_INVALID', 'NCKEY_RESIZE', 'NCKEY_UP', 'NCKEY_RIGHT', 'NCKEY_DOWN',
    'NCKEY_LEFT', 'NCKEY_INS', 'NCKEY_DEL', 'NCKEY_BACKSPACE', 'NCKEY_PGDOWN',
    'NCKEY_PGUP', 'NCKEY_HOME', 'NCKEY_END', 'NCKEY_F00', 'NCKEY_F01',
    'NCKEY_F02', 'NCKEY_F03', 'NCKEY_F04', 'NCKEY_F05', 'NCKEY_F06',
    'NCKEY_F07', 'NCKEY_F08', 'NCKEY_F09', 'NCKEY_F10', 'NCKEY_F11',
    'NCKEY_F12', 'NCKEY_F13', 'NCKEY_F14', 'NCKEY_F15', 'NCKEY_F16',
    'NCKEY_F17', 'NCKEY_F18', 'NCKEY_F19', 'NCKEY_F20', 'NCKEY_F21',
    'NCKEY_F22', 'NCKEY_F23', 'NCKEY_F24', 'NCKEY_F25', 'NCKEY_F26',
    'NCKEY_F27', 'NCKEY_F28', 'NCKEY_F29', 'NCKEY_F30', 'NCKEY_F31',
    'NCKEY_F32', 'NCKEY_F33', 'NCKEY_F34', 'NCKEY_F35', 'NCKEY_F36',
    'NCKEY_F37', 'NCKEY_F38', 'NCKEY_F39', 'NCKEY_F40', 'NCKEY_F41',
    'NCKEY_F42', 'NCKEY_F43', 'NCKEY_F44', 'NCKEY_F45', 'NCKEY_F46',
    'NCKEY_F47', 'NCKEY_F48', 'NCKEY_F49', 'NCKEY_F50', 'NCKEY_F51',
    'NCKEY_F52', 'NCKEY_F53', 'NCKEY_F54', 'NCKEY_F55', 'NCKEY_F56',
    'NCKEY_F57', 'NCKEY_F58', 'NCKEY_F59', 'NCKEY_F60', 'NCKEY_ENTER',
    'NCKEY_CLS', 'NCKEY_DLEFT', 'NCKEY_DRIGHT', 'NCKEY_ULEFT', 'NCKEY_URIGHT',
    'NCKEY_CENTER', 'NCKEY_BEGIN', 'NCKEY_CANCEL', 'NCKEY_CLOSE',
    'NCKEY_COMMAND', 'NCKEY_COPY', 'NCKEY_EXIT', 'NCKEY_PRINT',
    'NCKEY_REFRESH', 'NCKEY_SEPARATOR', 'NCKEY_CAPS_LOCK',
    'NCKEY_SCROLL_LOCK', 'NCKEY_NUM_LOCK', 'NCKEY_PRINT_SCREEN', 'NCKEY_PAUSE',
    'NCKEY_MENU', 'NCKEY_MEDIA_PLAY', 'NCKEY_MEDIA_PAUSE',
    'NCKEY_MEDIA_PPAUSE', 'NCKEY_MEDIA_REV', 'NCKEY_MEDIA_STOP',
    'NCKEY_MEDIA_FF', 'NCKEY_MEDIA_REWIND', 'NCKEY_MEDIA_NEXT',
    'NCKEY_MEDIA_PREV', 'NCKEY_MEDIA_RECORD', 'NCKEY_MEDIA_LVOL',
    'NCKEY_MEDIA_RVOL', 'NCKEY_MEDIA_MUTE', 'NCKEY_LSHIFT', 'NCKEY_LCTRL',
    'NCKEY_LALT', 'NCKEY_LSUPER', 'NCKEY_LHYPER', 'NCKEY_LMETA', 'NCKEY_RSHIFT',
    'NCKEY_RCTRL', 'NCKEY_RALT', 'NCKEY_RSUPER', 'NCKEY_RHYPER', 'NCKEY_RMETA',
    'NCKEY_L3SHIFT', 'NCKEY_L5SHIFT', 'NCKEY_MOTION', 'NCKEY_BUTTON1',
    'NCKEY_BUTTON2', 'NCKEY_BUTTON3', 'NCKEY_BUTTON4', 'NCKEY_BUTTON5',
    'NCKEY_BUTTON6', 'NCKEY_BUTTON7', 'NCKEY_BUTTON8', 'NCKEY_BUTTON9',
    'NCKEY_BUTTON10', 'NCKEY_BUTTON11', 'NCKEY_SIGNAL', 'NCKEY_EOF',
    'NCKEY_SCROLL_UP', 'NCKEY_SCROLL_DOWN', 'NCKEY_RETURN', 'NCKEY_TAB',
    'NCKEY_ESC', 'NCKEY_SPACE', 'NCKEY_MOD_SHIFT', 'NCKEY_MOD_ALT',
    'NCKEY_MOD_CTRL', 'NCKEY_MOD_SUPER', 'NCKEY_MOD_HYPER', 'NCKEY_MOD_META',
    'NCKEY_MOD_CAPSLOCK', 'NCKEY_MOD_NUMLOCK',

    'ncchannel_alpha', 'ncchannel_b', 'ncchannel_default_p', 'ncchannel_g',
    'ncchannel_palindex', 'ncchannel_palindex_p', 'ncchannel_r',
    'ncchannel_rgb8',
    'ncchannel_rgb_initializer', 'ncchannel_set', 'ncchannel_set_alpha',
    'ncchannel_set_default', 'ncchannel_set_palindex', 'ncchannel_set_rgb8',
    'ncchannel_set_rgb8_clipped', 'ncchannels_bchannel', 'ncchannels_bg_alpha',
    'ncchannels_bg_default_p', 'ncchannels_bg_palindex',
    'ncchannels_bg_palindex_p', 'ncchannels_bg_rgb', 'ncchannels_bg_rgb8',
    'ncchannels_combine', 'ncchannels_fchannel', 'ncchannels_fg_alpha',
    'ncchannels_fg_default_p', 'ncchannels_fg_palindex',
    'ncchannels_fg_palindex_p', 'ncchannels_fg_rgb', 'ncchannels_fg_rgb8',
    'ncchannels_rgb_initializer', 'ncchannels_set_bchannel',
    'ncchannels_set_bg_alpha', 'ncchannels_set_bg_default',
    'ncchannels_set_bg_palindex', 'ncchannels_set_bg_rgb',
    'ncchannels_set_bg_rgb8', 'ncchannels_set_bg_rgb8_clipped',
    'ncchannels_set_fchannel', 'ncchannels_set_fg_alpha',
    'ncchannels_set_fg_default', 'ncchannels_set_fg_palindex',
    'ncchannels_set_fg_rgb', 'ncchannels_set_fg_rgb8',
    'ncchannels_set_fg_rgb8_clipped',

    'ncstrwidth', 'notcurses_version', 'notcurses_version_components',

    'NCBOXASCII', 'NCBOXDOUBLE', 'NCBOXHEAVY', 'NCBOXLIGHT', 'NCBOXOUTER',
    'NCBOXROUND',

    'box', 'rgb',
)
